### ISSUE TITLE
event-ingestion-service not available via Yarn

### ISSUE THREAD

**Issue by andreasmartin** [voiceflow/general-runtime#341]
Dear VoiceFlow Dev Team and @frankgu968, with [this commit](https://github.com/voiceflow/general-runtime/blob/6d0786777959161d2cd363e77083f02783bd019f/package.json#L24) you have introduced the following package: event-ingestion-service

Unfortunately, it does not seem to be available via Yarn (Package Manager). Would it be possible for you to adapt your pipeline so that this package is available?

By the way: a really great project—your runtime!

**Comment by andreasmartin** [comment]
Dear @jonahsnider, do you think it would be possible to make the `event-ingestion-service` package available? There is also a #345 second issue open related to this.

**Comment by trs** [comment]
Sorry for this oversight. We've just made the `event-ingestion-service` package public. It may take a moment to propagate through npm, but you should be able to install it.
