### ISSUE TITLE
Some packages are not available via Yarn/npm

### ISSUE THREAD

**Issue by andreasmartin** [voiceflow/general-runtime#584]
Dear VoiceFlow Dev Team (@DecathectZero and @effervescentia), I have some issues with fetching packages, which are:
`@voiceflow/sdk-common/-/sdk-common-1.9.0.tgz`
`@voiceflow/sdk-auth/-/sdk-auth-2.4.2.tgz`
`@voiceflow/orval-fetch/-/orval-fetch-1.2.0.tgz`
`@voiceflow/orval-fetch/-/orval-fetch-1.1.2.tgz`
`@voiceflow/sdk-billing/-/sdk-billing-1.15.25.tgz`

Unfortunately, it does not seem to be available via Yarn/npm (package manager). Would it be possible for you to adapt your pipeline so that these packages becoming available?

**Comment by schwasa** [comment]
Dear VoiceFlow team (@DecathectZero and @effervescentia). Do you have any idea/news for us concerning this topic? Thank you very much.

**Comment by charutapande** [comment]
I am following this update too (@DecathectZero, @effervescentia)...is it planned any time soon? Thank you!

**Comment by andreasmartin** [comment]
It looks like we need to rework our build system because of the optional dependencies.
